source("./Reproduction_BICGLM/A1_10.R")
rm(list = ls())
source("./Reproduction_BICGLM/A1_30.R")
rm(list = ls())
source("./Reproduction_BICGLM/A1_50.R")
rm(list = ls())
source("./Reproduction_BICGLM/A1_50_02.R")
rm(list = ls())
source("./Reproduction_BICGLM/A1_50_005.R")
rm(list = ls())
source("./Reproduction_BICGLM/A1_50_0025.R")
rm(list = ls())

source("./Reproduction_BICGLM/A2_0.R")
rm(list = ls())
source("./Reproduction_BICGLM/A2_025.R")
rm(list = ls())
source("./Reproduction_BICGLM/B.R")
rm(list = ls())
source("./Reproduction_BICGLM/C.R")
rm(list = ls())
